# Generated by Django 6.0.3 on 2026-03-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('series', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rarity', models.CharField(max_length=10)),
                ('clan', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='cards/')),
            ],
        ),
    ]
